### ISSUE TITLE
Probleme im Menü 

### ISSUE THREAD

**Issue by le-Vinyl** [MathiasHun/FS22_gameplay_ExtendedOwnedItems#1]
Hallo. 
Danke für diesen super mod!
Leider habe ich ein Problem in Verbindung mit:
- echte fahrzeugpannen (github)
Und 
- erweitertes Kreditsystem (modhub)
Aufgefallen im multiplayer.

Bei beiden friert das Spiel im jeweiligen Menü ein und zeigt "wilde" (nicht lesbare) Zeichen an

Log:
Error: Running LUA method "mouseEvent"
....../...../mods/FS22_ExrendedOwnedItems/extendedOwnedItems.lua:55:attempt to index field´ownedItemsProfitLoss´(a nil value)

**Comment by le-Vinyl** [comment]
> Hallo. Danke für diesen super mod! Leider habe ich ein Problem in Verbindung mit:
> 
>     * echte fahrzeugpannen (github)
>       Und
> 
>     * erweitertes Kreditsystem (modhub)
>       Aufgefallen im multiplayer.
> 
> 
> Bei beiden friert das Spiel im jeweiligen Menü ein und zeigt "wilde" (nicht lesbare) Zeichen an

Log:
Error: Running LUA method "mouseEvent"
....../...../mods/FS22_ExrendedOwnedItems/extendedOwnedItems.lua:55:attempt to index field´ownedItemsProfitLoss´(a nil value)

**Comment by MathiasHun** [comment]
Please, [Download the latest developer version](https://filesadmin.com/96864e3db45e3be3/FS22_gameplay_ExtendedOwnedItems.zip)
